Sprint2/step1
nikit3113/yandex-react-burgrer pull request #3
Opened 2022-05-03 15:49 UTC by nikit3113

2022-05-03 17:08 UTC, andryxxa93 requested changes
Доброго времени суток! 

Проделана большая работа! Код написан хорошо, аккуратно и понятно. Использованы понятные названия функций и переменных, контекст добавлен верно и работает корректно. 

Однако есть несколько моментов, которые не соответствуют требованиям и макету.

Необходимо исправить:
1) Надо добавить проверку ответа сервера - res.ok.
2) Подсчеты и обращения к серверу и любую другую логику не стоит делать внутри верстки, её стоит вынести в отдельные функции. 
3) Картинка в модальном окне с деталями заказа не соответствует макету.

Можно улучшить:
1) Компоненты внутрь которых ничего не передается можно сделать самозакрывающимися.
2) Убрать повторяющиеся блоки верстки в отдельные компоненты для возможности переиспользования.
3) Убрать console.log
4) Использовать деструктуризацию вместо простой передачи props.

На данном этапе вы можете не исправлять замечания помеченные как "Необходимо исправить", но на следующем они станут обязательными к исправлению.
Замечания помеченные как "Можно улучшить" исправлять обязательно, но они помогут сделать код чище и избежать ошибок в будущем.

В pull request вы найдете комментарии с более развернутым описанием проблемы и возможными путями её решения. 

Удачных правок!

2022-05-03 17:08 UTC, andryxxa93 commented on src/api/api.js
> +}
Надо исправить
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-05-03 17:08 UTC, andryxxa93 commented on src/components/app/app.jsx
> +        <OrderDetails orderNumber={orderModal.orderNumber}></OrderDetails>
Можно улучшить: 
Компоненты внутрь которых ничего не передается можно сделать самозакрывающимися, вот так `<OrderDetails orderNumber={orderModal.orderNumber}/>`

2022-05-03 17:08 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
>  const IngredientCard = (props) => {
Можно улучшить: лучше везде вместо props использовать деструктуризацию, это делает работу компонента более понятной и код легче отлаживаемым.

2022-05-03 17:08 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +              .catch(() => console.log('error post order'))
Необходимо исправить: логика должна быть разделена с представлением. Необходимо вынести запрос из верстки. Так же лучше не оставлять console.log в проекте, а использовать только для разработки.

2022-05-03 17:08 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
>  const Tabs = () => {
Можно улучшить:
внутри компонента есть повторяющаяся верстка, её можно вынести в отдельный компонент и переиспользовать. То же касается и компонента IngredientList

2022-05-03 17:08 UTC, andryxxa93 commented on src/components/order-details/order-details.jsx
> +        <CheckMarkIcon type={'primary'}/>
Необходимо исправить:
Картинка не соответствует той что в макете figma.
<img width="573" alt="Снимок экрана 2022-05-03 в 19 41 36" src="https://user-images.githubusercontent.com/60173362/166500014-52652282-4087-48cf-85e6-af4bf37deea6.png">
<img width="660" alt="Снимок экрана 2022-05-03 в 19 42 41" src="https://user-images.githubusercontent.com/60173362/166500064-6ef96762-2c38-49f5-b515-e2d78c39526c.png">

2022-05-03 17:08 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
>              <CurrencyIcon type={'primary'}/>
Необходимо исправить: логику необходимо вынести из верстки в функцию, которую так же следует обернуть в хук useMemo, чтобы избежать лишних вычислений.

2022-05-13 06:23 UTC, andryxxa93 approved these changes
Проделана большая работа! Все замечания учтены и добавлен новый функционал. Вы отлично справились. Ваша работа принята.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок.

Удачного продолжения обучения!

2022-05-13 06:23 UTC, andryxxa93 commented on src/components/app/app.jsx
> +          alert(error);
**Можно улучшить**
Alert не самый лучший вариант оповещения об ошибке. Как вариант можно показывать модальное окно (которое уже есть в проекте) с текстом "Что-то пошло не так, попробуйте ещё раз позже".

2022-05-13 06:23 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
>  function BurgerConstructor(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-05-13 06:23 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +  }, [filling, bun]);
**Отлично**!
Правильно использовали useMemo и reduce

2022-05-13 06:23 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
>          {count ? <Counter count={count}/> : null}
**Можно улучшить**
Тут можно использовать оператор AND (&&) вместо тернарного оператора. Если один из операндов будет false, то оператор вернет false и react не будет рендерить ничего. 
https://ru.react.js.org/docs/conditional-rendering.html

2022-05-13 06:23 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.js
> +  }
**Отлично!**
Добавили скролл по категориям

2022-05-13 06:42 UTC, nikit3113 commented on src/components/app/app.jsx
> +          alert(error);
Спасибо. Там есть ещё несколько таких недоработок. Например, пока нету состояния загрузки данных с сервера. В дальнейшем обязательно исправлю этот момент. Спасибо, за подсказку с модальным окном! :)

2022-05-13 06:46 UTC, nikit3113 commented on src/components/burger-ingredients/burger-ingredients.js
>          {count ? <Counter count={count}/> : null}
Точно! Не знаю, что на меня нашло) Спасибо)

2022-05-13 06:54 UTC, merged