Sprint 6/step 1
nikit3113/yandex-react-burgrer pull request #8
Opened 2022-12-05 07:52 UTC by nikit3113

2022-12-05 11:49 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙

Вы проделали **хорошую** работу по покрытию вашего проекта тестами, учли практически все тест-кейсы в рамках покрытия редьюсеров, использовали моки для API, протестировав создание заказа, так держать 👍

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует добавить тест на открытие модального окна с подробностями об ингредиенте;
- Следует обеспечить полное покрытие всех строк кода редьюсеров `ingredient` и `user` (см. https://disk.yandex.ru/i/c9ilhOfHBCnMuQ). Проверить эффективность покрытия вы можете воспользовавшись командой `npm test -- --coverage --watchAll=false`, результат будет как на скриншоте и покажет, какие именно строки кода осталось протестировать :)
- Проект некорректно опубликован на Github Pages, при попытке его просмотра отображается файл `README.md`, вместо непосредственно сайта. Предлагаю вам ознакомиться с гайдом, в котором описаны необходимые действия (см. https://github.com/gitname/react-gh-pages);

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Имеет смысл разделить один большой E2E тест на несколько меньших, например тестировать отдельно перетаскивание булки, перетаскивание ингредента, а потом уже в совокупности - весь заказ;
- При отправке заказа можно осуществлять проверку, правильный ли массив отправляется на сервер:
```javascript
.its("request.body")
      .should("deep.equal", {
        ingredients: ["1", "3", "4", "1"],
      });
```

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-12-05 11:49 UTC, randomroot commented on cypress/e2e/main-app-test.cy.ts
> +    cy.get('@orderButton').click();
🔴 **Нужно исправить:**

Следует убрать двойное нажатие на кнопку, т.к. это вызовет двойную отправку заказа

2022-12-05 11:49 UTC, randomroot commented on cypress/e2e/spec.cy.ts
> +  it('Does not do much!', () => {
🟡 **Можно улучшить:**

Тесты примеры имеет смысл удалять из проекта

2022-12-06 08:31 UTC, randomroot requested changes
**Здравствуйте!**

Вы произвели необходимые изменения, добавили тест с модальным окном, однако благодаря улучшенным E2E был выявлен ряд моментов, работающих в проекте некорректно, необходимо их **исправить** для успешной сдачи работы:

- Заказ отправляется только после двух нажатий на кнопку "Оформить заказ" (после первого происходит перезагрузка страницы с отправкой `user`, ошибка теста: https://disk.yandex.ru/i/glmAttjS1v2thw) - поэтому раньше тест успешно выполнялся, следует перепроверить код конструктора (обратите внимание на https://disk.yandex.ru/i/qyfsPbr5AOMiNw, такой запрос лучше сделать при старте приложения);

В качестве возможно **улучшения** ваших тестов, целесообразно также протестировать и закрытие модального окна по нажатию на `overlay`.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **тесты проходят успешно**.

---
**Хорошего вам дня!** 🐈

2022-12-06 09:22 UTC, nikit3113 commented
Двойное нажатие на кнопку нужно. Так как у нас нету активного пользователя мы переходим на страницу авторизации, там мы видим то у нас есть куки (которые мы настроили перед тестом). После этого происходит запрос на сервер для получения пользователя который мы успешно мокаем. И после этого уже идёт обратный редирект на страницу с конструктором. После чего я ещё раз нажимаю на кнопку авторизации. 
    На мой взгляд логика приложения правильная и всё отрабатывает так, как положено. То что мы подменой куков и моком данных пользователя заменяем часть теста не считаю ошибкой.

2022-12-06 09:31 UTC, randomroot commented
@nikit3113 обратите внимание, что данный процесс повторяется не только в тестах, но и при обычном запуске вашего проекта через браузер. Предположим, пользователь зашёл под своим аккаунтом, затем закрыл страницу и открыл в новой вкладке конструктор. Когда он соберёт заказ и нажмёт кнопку оформить, вместо того, чтобы открыло модальное окно и ушёл запрос на API (т.к. все условия соблюдены: заказ наполнен, пользователь авторизован, куки имеются) у него произойдет перезагрузка страницы и ему придётся повторно нажимать кнопку оформления, это является не совсем удачным UX. 

[screen-capture (1).webm](https://user-images.githubusercontent.com/15111821/205873456-b4730b18-14a1-4e59-91e5-801996aa1547.webm)

2022-12-06 10:00 UTC, nikit3113 commented
@randomroot 
Исправил.

2022-12-06 10:54 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-12-13 17:22 UTC, merged